import { useState } from 'react'
import { useAstraStore } from '@/lib/demo/store'
import { PATTERN_LABELS } from '@/lib/demo/patterns'

function formatDate(iso: string) {
  const d = new Date(iso)
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
}

function generateNoteText(user: { name: string }, patterns: any[], baseline: any): string {
  const today = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
  const rangeStart = new Date()
  rangeStart.setDate(rangeStart.getDate() - 90)
  const rangeStr = `${formatDate(rangeStart.toISOString().split('T')[0])} – ${today}`

  const activePatterns = patterns.filter((p) => p.isActive)
  const allPatterns = patterns

  const mainPattern = activePatterns[0] || allPatterns[0]

  return `ASTRA HEALTH PATTERN SUMMARY
Generated: ${today}
Period analysed: ${rangeStr}
Prepared by: ${user.name}

OVERVIEW
This summary was generated by Astra, a passive health pattern intelligence platform. It organises wearable and phone data to support personal awareness or optional clinical discussion.

This document does not diagnose, prescribe or provide medical advice.

────────────────────────────────

PATTERNS DETECTED (${allPatterns.length} total)

${allPatterns.map((p, i) => `${i + 1}. ${PATTERN_LABELS[p.patternType]}
   Period: ${formatDate(p.startDate)}${p.endDate ? ` – ${formatDate(p.endDate)}` : ' – Present (active)'}
   Duration: ${p.durationDays} days · Severity: ${p.severity} · Confidence: ${p.confidence}%
   ${p.recurrenceOf ? '↻ Recurrence of an earlier pattern of the same type' : ''}

   Summary: ${p.summary}

   Contributing signals:
${p.supportingSignals.map((s: any) => `   • ${s.label}: ${s.change}`).join('\n')}
`).join('\n')}

────────────────────────────────

PERSONAL BASELINE (30-day reference)

Sleep:          ${baseline.sleepDuration.low}h – ${baseline.sleepDuration.high}h  (avg ${baseline.sleepDuration.mean}h)
Resting HR:     ${baseline.restingHR.low} – ${baseline.restingHR.high} bpm  (avg ${baseline.restingHR.mean} bpm)
HRV:            ${baseline.hrv.low} – ${baseline.hrv.high} ms  (avg ${baseline.hrv.mean} ms)
Daily steps:    ${baseline.steps.low.toLocaleString()} – ${baseline.steps.high.toLocaleString()}  (avg ${baseline.steps.mean.toLocaleString()})

────────────────────────────────

SUGGESTED DISCUSSION AREAS
(If you choose to discuss with a clinician)

• Recurring changes in resting heart rate and HRV during identified periods
• Sleep disruption patterns and any associated low-energy days
• Activity tolerance — any relationship between high-activity periods and recovery
• Whether further monitoring or investigation is appropriate

────────────────────────────────

SAFETY NOTE
This summary does not diagnose, prescribe or provide medical advice. It organises user-owned wearable and contextual data to support personal understanding or optional clinical discussion. All data belongs to the user and was not shared with any third party.

Generated by Astra · Passive Health Pattern Intelligence`
}

export default function HealthNote() {
  const { user, patterns, baseline } = useAstraStore()
  const [showExport, setShowExport] = useState(false)
  const [copied, setCopied] = useState(false)

  const noteText = generateNoteText(user, patterns, baseline)

  const today = new Date()
  const rangeStart = new Date()
  rangeStart.setDate(today.getDate() - 90)

  const activePatterns = patterns.filter((p) => p.isActive)
  const resolvedPatterns = patterns.filter((p) => !p.isActive)

  async function handleCopy() {
    await navigator.clipboard.writeText(noteText)
    setCopied(true)
    setTimeout(() => setCopied(false), 2500)
  }

  function handlePrint() {
    const w = window.open('', '_blank')
    if (!w) return
    w.document.write(`<pre style="font-family:monospace;font-size:13px;white-space:pre-wrap;padding:32px;max-width:720px;margin:0 auto">${noteText}</pre>`)
    w.document.close()
    w.print()
  }

  return (
    <div className="screen-note">
      <h1 className="screen-title">Health Note</h1>
      <p className="screen-subtitle">
        An optional summary you own and control. Generate it, save it, or bring it to an appointment. Nothing is sent automatically.
      </p>

      {/* Period */}
      <div className="note-period">
        <span className="note-period-label">Period covered</span>
        <span className="note-period-value">
          {formatDate(rangeStart.toISOString().split('T')[0])} – {formatDate(today.toISOString().split('T')[0])}
        </span>
      </div>

      {/* Summary card */}
      <div className="note-summary-card">
        <div className="note-summary-title">Pattern summary</div>

        <div className="note-stat-row">
          <div className="note-stat">
            <span className="note-stat-value">{patterns.length}</span>
            <span className="note-stat-label">patterns detected</span>
          </div>
          <div className="note-stat">
            <span className="note-stat-value">{activePatterns.length}</span>
            <span className="note-stat-label">currently active</span>
          </div>
          <div className="note-stat">
            <span className="note-stat-value">2</span>
            <span className="note-stat-label">recurrences noted</span>
          </div>
        </div>

        {/* Main pattern */}
        {activePatterns[0] && (
          <div className="note-main-pattern">
            <div className="note-main-pattern-label">Primary active pattern</div>
            <div className="note-main-pattern-name">{PATTERN_LABELS[activePatterns[0].patternType]}</div>
            <p className="note-main-pattern-summary">{activePatterns[0].summary}</p>
          </div>
        )}

        {/* Pattern list */}
        <div className="note-pattern-list">
          {patterns.map((p) => (
            <div key={p.id} className="note-pattern-item">
              <div className="note-pattern-item-left">
                <span className={`note-pattern-dot ${p.isActive ? 'dot-active' : 'dot-resolved'}`} />
                <span className="note-pattern-item-name">{PATTERN_LABELS[p.patternType]}</span>
                {p.recurrenceOf && <span className="note-recurrence-tag">↻ recurrence</span>}
              </div>
              <span className="note-pattern-item-date">
                {formatDate(p.startDate)}
                {p.endDate ? ` – ${formatDate(p.endDate)}` : ' – Present'}
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* Baseline snapshot */}
      <div className="note-baseline-card">
        <div className="note-baseline-title">Your personal baseline (30-day reference)</div>
        <div className="note-baseline-grid">
          {[
            { label: 'Sleep',      value: `${baseline.sleepDuration.mean}h avg`,      range: `${baseline.sleepDuration.low}h – ${baseline.sleepDuration.high}h` },
            { label: 'Resting HR', value: `${baseline.restingHR.mean} bpm avg`,       range: `${baseline.restingHR.low} – ${baseline.restingHR.high} bpm` },
            { label: 'HRV',        value: `${baseline.hrv.mean} ms avg`,              range: `${baseline.hrv.low} – ${baseline.hrv.high} ms` },
            { label: 'Steps',      value: `${baseline.steps.mean.toLocaleString()} avg`, range: `${baseline.steps.low.toLocaleString()} – ${baseline.steps.high.toLocaleString()}` },
          ].map((item) => (
            <div key={item.label} className="note-baseline-item">
              <span className="note-baseline-item-label">{item.label}</span>
              <span className="note-baseline-item-value">{item.value}</span>
              <span className="note-baseline-item-range">{item.range}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Discussion areas */}
      <div className="note-discuss-card">
        <div className="note-discuss-title">Suggested discussion areas</div>
        <p className="note-discuss-intro">If you choose to discuss with a clinician, these non-diagnostic topics relate to the patterns Astra detected:</p>
        <ul className="note-discuss-list">
          <li>Recurring changes in resting heart rate and HRV</li>
          <li>Sleep disruption and any associated low-energy days</li>
          <li>Activity tolerance and recovery periods</li>
          <li>Whether further monitoring or investigation is appropriate</li>
        </ul>
      </div>

      {/* Export actions */}
      <div className="note-actions">
        <button className="note-btn-primary" onClick={() => setShowExport(true)}>
          Preview full note
        </button>
        <button className="note-btn-secondary" onClick={handleCopy}>
          {copied ? 'Copied ✓' : 'Copy to clipboard'}
        </button>
        <button className="note-btn-secondary" onClick={handlePrint}>
          Print / Save as PDF
        </button>
      </div>

      <p className="screen-safety">
        This note does not diagnose, prescribe or constitute medical advice. It organises your own wearable data to support personal understanding or optional clinical discussion. All data is yours.
      </p>

      {/* Export preview modal */}
      {showExport && (
        <div className="note-modal-overlay" onClick={() => setShowExport(false)}>
          <div className="note-modal" onClick={(e) => e.stopPropagation()}>
            <div className="note-modal-header">
              <span className="note-modal-title">Health Note Preview</span>
              <button className="note-modal-close" onClick={() => setShowExport(false)}>✕</button>
            </div>
            <pre className="note-modal-text">{noteText}</pre>
            <div className="note-modal-footer">
              <button className="note-btn-primary" onClick={handleCopy}>{copied ? 'Copied ✓' : 'Copy'}</button>
              <button className="note-btn-secondary" onClick={handlePrint}>Print</button>
              <button className="note-btn-ghost" onClick={() => setShowExport(false)}>Close</button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
